name: glazer

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  polish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint codebase
        uses: docker://github/super-linter:v2.2.0
